name: Build & Test

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2022]

    steps:
    - if: matrix.os == 'windows-2022'
      name: Install Cppcheck (Windows)
      run: |
        choco install -y --ignore-package-exit-codes cppcheck
        echo "C:\Program Files\Cppcheck" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - if: matrix.os == 'windows-2022'
      name: Configure MSVC (Windows)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Install Meson and Ninja
      run: |
        pip3 install --upgrade meson ninja

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build - Release
      run: |
        meson setup --buildtype=release builddir
        meson compile -C builddir

    - name: Test - Release
      run: |
        meson test -vC builddir

    - if: matrix.os == 'windows-2022'
      name: Build - Debug (Windows)
      run: |
        meson setup --buildtype=debug --wipe builddir
        meson compile -C builddir

    - if: matrix.os == 'windows-2022'
      name: Test - Debug (Windows)
      run: |
        meson test -vC builddir
